files:
  initial_rubrics: null
  responses_file: null
  output_dir: "workflow_outputs"

workflow:
  # Style is now always "improve" (full replacement)
  initial_responses_per_prompt: 2
  max_iterations: 1
  sample_size: null

models:
  # Backend is always API now
  verifier: "openai/gpt-4.1-mini"
  rubric_generator: "openai/gpt-4.1"


api:
  workers: 64
  max_retries: 1
  retry_temperature: 1.0

grading:
  skip_scoring: true # if true: skip scoring step, assign all responses score 0 (making them tied), randomly select 2 for rubric improvement, continue until max_iterations
